@startuml
skin rose
skinparam backgroundColor #EEEBDC
hide circle
/' skinparam linetype ortho '/
/' left to right direction '/

entity User {
  Id : serial <<PK>>
  --
  Auth0ID
  NotifyOnExpiration
  NotifyOnDeadline
  NotifyOnThreshold
  NotifyOnInsufficientResources
}

entity ItemType {
  Id : serial <<PK>>
  --
  Name
  Description
  BaseMeasurementUnit
  DefaultDisplayMeasurementUnit
  DefaultQuantity
  ShortageTrashold
  PictureName
  PictureSource
}

entity Item {
  Id : serial <<PK>>
  --
  Description
  Quantity
  ExpirationDate
  DisplayMeasurementUnit
  PurchasePrice
}

entity Picture {
  Id : serial <<PK>>
  --
  BlobId
  Filetyp
}

entity Tag {
  Id : serial <<PK>>
  --
  Name
  Color
}

User ||-d-o{ ItemType
User ||-d-o{ Item

ItemType }o-d-o{ Tag
Item }o-d-o{ Tag

Item }o-r-|| ItemType

ItemType ||--|| Picture

@enduml
