@startuml
skin rose
skinparam backgroundColor #EEEBDC
hide circle
skinparam linetype ortho
left to right direction

entity User {
  Id : serial <<PK>>
  --
  Auth0ID
  Email
  NotifyOnExpiration
  NotifyOnDeadline
  NotifyOnThreshold
  NotifyOnInsufficientResources
}


entity ItemType {
  Id : serial <<PK>>
  --
  Name
  Description
  Category
  BaseMeasurementUnit
  DefaultQuantity
  Width
  Height
  Depth
}

entity Picture {
  Id : serial <<PK>>
  --
  BlobId
  Filetyp
}

User ||--o{ ItemType
ItemType ||--|| Picture
@enduml
