@startuml
skin rose
skinparam backgroundColor #EEEBDC
hide circle
/' skinparam linetype ortho '/
/' left to right direction '/

entity User {
  Id : serial <<PK>>
  --
  Auth0ID : varchar(255)
  NotifyOnExpiration : boolean
  NotifyOnDeadline : boolean
  NotifyOnThreshold : boolean
  NotifyOnInsufficientResources : boolean
  --
  CreatedAt : DateTime
  UpdatedAt : DateTime
}

entity ItemType {
  Id : serial <<PK>>
  --
  UserId : serial <<FK>>
  Picture : serial <<FK>>
  --
  Name : varchar(255)
  Description : varchar(512)
  BaseMeasurementUnit : varchar(255)
  DefaultDisplayMeasurementUnit : varchar (255)
  DefaultQuantity : float
  ShortageTrashold : float
  --
  CreatedAt : DateTime
  UpdatedAt : DateTime
  DeleatedAt : DateTime
}

entity Picture {
  Id : serial <<PK>>
  --
  BlobId : uuid
  Filetype: varchar(8)
  --
  CreatedAt : DateTime
  UpdatedAt : DateTime
  DeleatedAt : DateTime
}

entity Item {
  Id : serial <<PK>>
  --
  UserId : serial <<FK>>
  ItemTypeId : serial <<FK>>
  --
  Description : varchar(512)
  Quantity : float
  ExpirationDate : DateTime
  DisplayMeasurementUnit : varchar (255)
  PurchasePrice : float
  --
  CreatedAt : DateTime
  UpdatedAt : DateTime
  DeleatedAt : DateTime
}

entity ItemToTag {
  Id : serial <<PK>>
  --
  ItemId : serial <<FK>> <<PK>>
  TagId : serial <<FK>> <<PK>>
}

entity ItemTypeToTag {
  Id : serial <<PK>>
  --
  ItemTypeId : serial <<FK>> <<PK>>
  TagId : serial <<FK>> <<PK>>
}

entity Tag {
  Id : serial <<PK>>
  --
  UserId : serial <<FK>>
  --
  Name : varchar(255)
  Color : varchar (255)
  --
  CreatedAt : DateTime
  UpdatedAt : DateTime
  DeleatedAt : DateTime
}

User ||-d-o{ ItemType
User ||-d-o{ Item
ItemType ||-l-|| Picture
ItemType ||--r--o{ Item

Item ||-d-o{ ItemToTag
Tag ||-r-o{ ItemToTag

ItemType ||-d-o{ ItemTypeToTag
Tag ||-l-o{ ItemTypeToTag

@enduml
