@startuml
skin rose
skinparam backgroundColor #EEEBDC
/' left to right direction '/
/' skinparam linetype ortho '/

object "John: User" as UserJohn {
    Id = 0
    NotifyOnExpiration = True
    NotifyOnDeadline = True
    NotifyOnThreshold = True
    NotifyOnInsufficientResources = True
}
object "Jane: User" as UserJane {
    Id = 1
    NotifyOnExpiration = True
    NotifyOnDeadline = False
    NotifyOnThreshold = False
    NotifyOnInsufficientResources = True
}

object "John's Catalog: Catalog" as JohnCatalog {
    Id = 0
}
object "Jane's Catalog: Catalog" as JaneCatalog {
    Id = 1
}

object "John's Inventory: Inventory" as JohnInventory {
    Id = 0
}
object "Jane's Inventory: Inventory" as JaneInventory {
    Id = 1
}

object "Tools: Tag" as TagTools {
    Id = 100
    Name = "Tools"
    Color = "Red"
}

object "Scissors: ItemType" as Scissors {
    Id = 0
    Name = "Scissors"
    Description = "amazing scissors"
    BaseMeasurementUnit = "piece"
    DefaultDisplayMeasurementUnit = "piece"
    DefaultQuantity = 1
    ShortageTrashold = 1
    PictureName = "scissors-picture"
    PictureSource = "scissors-picture.png"
}

object "Needles: ItemType" as Needles {
    Id = 1
    Name = "Needles"
    Description = "amazing needles"
    BaseMeasurementUnit = "pack"
    DefaultDisplayMeasurementUnit = "pack"
    DefaultQuantity = 10
    ShortageTrashold = 5
    PictureName = "needles-picture"
    PictureSource = "needles-picture.png"
}

object "Big Scissors: Item" as BigScissors {
    Id = 1000
    Description = "My big red scissors"
    Quantity = 1
    ExpirationDate = null
    DisplayMeasurementUnit = "piece"
    PurchasePrice = 15.99
}

object "Steel Needles: Item" as SteelNeedles {
    Id = 1001
    Description = "Amazing steel needles"
    Quantity = 1
    ExpirationDate = null
    DisplayMeasurementUnit = "pack"
    PurchasePrice = 4.99
}

UserJohn --d-- JohnCatalog
UserJohn -r- JohnInventory
JohnCatalog -r- Scissors
JohnInventory -- BigScissors
BigScissors --> Scissors

UserJane --d-- JaneCatalog
UserJane -l- JaneInventory
JaneCatalog -l- Needles
JaneInventory -- SteelNeedles
SteelNeedles --> Needles

TagTools -d- Scissors
TagTools -u- BigScissors
TagTools -d- Needles
TagTools -u- SteelNeedles

@enduml
